[package]
name = "mucodec"
version = "0.1.0"
edition = "2021"

[dependencies]
hex = { version = "0.4.3", default-features = false }
onlyerror = { version = "0.1.4", default-features = false }
base64 = { version = "0.22.1", features = ["alloc"] }

[dev-dependencies]
criterion = { version = "0.5.1" }
hex = { version = "0.4.3" }
proptest = "1.5.0"
rand = "0.8.5"
test-strategy = "0.4.0"
paste = "1.0"

[[bench]]
name = "all"
path = "benches/bench_all.rs"
harness = false
